# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BulkUpdateRequestUpdateFields(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, course: str=None, batch: str=None, year_of_joining: str=None):  # noqa: E501
        """BulkUpdateRequestUpdateFields - a model defined in Swagger

        :param course: The course of this BulkUpdateRequestUpdateFields.  # noqa: E501
        :type course: str
        :param batch: The batch of this BulkUpdateRequestUpdateFields.  # noqa: E501
        :type batch: str
        :param year_of_joining: The year_of_joining of this BulkUpdateRequestUpdateFields.  # noqa: E501
        :type year_of_joining: str
        """
        self.swagger_types = {
            'course': str,
            'batch': str,
            'year_of_joining': str
        }

        self.attribute_map = {
            'course': 'course',
            'batch': 'batch',
            'year_of_joining': 'yearOfJoining'
        }
        self._course = course
        self._batch = batch
        self._year_of_joining = year_of_joining

    @classmethod
    def from_dict(cls, dikt) -> 'BulkUpdateRequestUpdateFields':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BulkUpdateRequest_updateFields of this BulkUpdateRequestUpdateFields.  # noqa: E501
        :rtype: BulkUpdateRequestUpdateFields
        """
        return util.deserialize_model(dikt, cls)

    @property
    def course(self) -> str:
        """Gets the course of this BulkUpdateRequestUpdateFields.

        Updated course for students  # noqa: E501

        :return: The course of this BulkUpdateRequestUpdateFields.
        :rtype: str
        """
        return self._course

    @course.setter
    def course(self, course: str):
        """Sets the course of this BulkUpdateRequestUpdateFields.

        Updated course for students  # noqa: E501

        :param course: The course of this BulkUpdateRequestUpdateFields.
        :type course: str
        """

        self._course = course

    @property
    def batch(self) -> str:
        """Gets the batch of this BulkUpdateRequestUpdateFields.

        Updated batch for students  # noqa: E501

        :return: The batch of this BulkUpdateRequestUpdateFields.
        :rtype: str
        """
        return self._batch

    @batch.setter
    def batch(self, batch: str):
        """Sets the batch of this BulkUpdateRequestUpdateFields.

        Updated batch for students  # noqa: E501

        :param batch: The batch of this BulkUpdateRequestUpdateFields.
        :type batch: str
        """

        self._batch = batch

    @property
    def year_of_joining(self) -> str:
        """Gets the year_of_joining of this BulkUpdateRequestUpdateFields.

        Updated year of joining for students  # noqa: E501

        :return: The year_of_joining of this BulkUpdateRequestUpdateFields.
        :rtype: str
        """
        return self._year_of_joining

    @year_of_joining.setter
    def year_of_joining(self, year_of_joining: str):
        """Sets the year_of_joining of this BulkUpdateRequestUpdateFields.

        Updated year of joining for students  # noqa: E501

        :param year_of_joining: The year_of_joining of this BulkUpdateRequestUpdateFields.
        :type year_of_joining: str
        """

        self._year_of_joining = year_of_joining
