# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DbGetRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, collection_name: str=None, query: object=None, type: str=None):  # noqa: E501
        """DbGetRequest - a model defined in Swagger

        :param collection_name: The collection_name of this DbGetRequest.  # noqa: E501
        :type collection_name: str
        :param query: The query of this DbGetRequest.  # noqa: E501
        :type query: object
        :param type: The type of this DbGetRequest.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'collection_name': str,
            'query': object,
            'type': str
        }

        self.attribute_map = {
            'collection_name': 'collectionName',
            'query': 'query',
            'type': 'type'
        }
        self._collection_name = collection_name
        self._query = query
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'DbGetRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DbGetRequest of this DbGetRequest.  # noqa: E501
        :rtype: DbGetRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def collection_name(self) -> str:
        """Gets the collection_name of this DbGetRequest.


        :return: The collection_name of this DbGetRequest.
        :rtype: str
        """
        return self._collection_name

    @collection_name.setter
    def collection_name(self, collection_name: str):
        """Sets the collection_name of this DbGetRequest.


        :param collection_name: The collection_name of this DbGetRequest.
        :type collection_name: str
        """

        self._collection_name = collection_name

    @property
    def query(self) -> object:
        """Gets the query of this DbGetRequest.


        :return: The query of this DbGetRequest.
        :rtype: object
        """
        return self._query

    @query.setter
    def query(self, query: object):
        """Sets the query of this DbGetRequest.


        :param query: The query of this DbGetRequest.
        :type query: object
        """

        self._query = query

    @property
    def type(self) -> str:
        """Gets the type of this DbGetRequest.


        :return: The type of this DbGetRequest.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this DbGetRequest.


        :param type: The type of this DbGetRequest.
        :type type: str
        """
        allowed_values = ["findOne", "findMany"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type
