# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.report_data_report import ReportDataReport  # noqa: F401,E501
from swagger_server import util


class ReportData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, report: List[ReportDataReport]=None):  # noqa: E501
        """ReportData - a model defined in Swagger

        :param report: The report of this ReportData.  # noqa: E501
        :type report: List[ReportDataReport]
        """
        self.swagger_types = {
            'report': List[ReportDataReport]
        }

        self.attribute_map = {
            'report': 'report'
        }
        self._report = report

    @classmethod
    def from_dict(cls, dikt) -> 'ReportData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReportData of this ReportData.  # noqa: E501
        :rtype: ReportData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def report(self) -> List[ReportDataReport]:
        """Gets the report of this ReportData.


        :return: The report of this ReportData.
        :rtype: List[ReportDataReport]
        """
        return self._report

    @report.setter
    def report(self, report: List[ReportDataReport]):
        """Sets the report of this ReportData.


        :param report: The report of this ReportData.
        :type report: List[ReportDataReport]
        """

        self._report = report
