# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Response(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: object=None, message: str=None, error: str=None):  # noqa: E501
        """Response - a model defined in Swagger

        :param data: The data of this Response.  # noqa: E501
        :type data: object
        :param message: The message of this Response.  # noqa: E501
        :type message: str
        :param error: The error of this Response.  # noqa: E501
        :type error: str
        """
        self.swagger_types = {
            'data': object,
            'message': str,
            'error': str
        }

        self.attribute_map = {
            'data': 'data',
            'message': 'message',
            'error': 'error'
        }
        self._data = data
        self._message = message
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Response of this Response.  # noqa: E501
        :rtype: Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> object:
        """Gets the data of this Response.


        :return: The data of this Response.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this Response.


        :param data: The data of this Response.
        :type data: object
        """

        self._data = data

    @property
    def message(self) -> str:
        """Gets the message of this Response.


        :return: The message of this Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Response.


        :param message: The message of this Response.
        :type message: str
        """

        self._message = message

    @property
    def error(self) -> str:
        """Gets the error of this Response.


        :return: The error of this Response.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this Response.


        :param error: The error of this Response.
        :type error: str
        """

        self._error = error
